"""add field title

Revision ID: 423ce49dfa62
Revises: e209f0ff4ad2
Create Date: 2018-06-29 01:19:17.199752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423ce49dfa62'
down_revision = 'e209f0ff4ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
