"""add jobs table

Revision ID: e209f0ff4ad2
Revises: 25038ff93427
Create Date: 2018-06-29 01:05:46.787850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e209f0ff4ad2'
down_revision = '25038ff93427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('github_issues_number', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_time'), 'jobs', ['created_time'], unique=False)
    op.create_index(op.f('ix_jobs_updated_time'), 'jobs', ['updated_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_updated_time'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_time'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
